meta_product_name: "Game On!"
meta_title: "Game On! - Legendary Host Activated!"
meta_description: "Easy to use organiser to set up your next game party! Give your guest the choice to also have their say!"
meta_image: "login_logo.png" # should exist in `app/assets/images/`
