meta_product_name: "Game On!"
meta_title: "Game On! - Let the fun begin!"
meta_description: "Easy to use organiser to set up your next game party! Give your guest the choice to also have their say!"
meta_image: "op_image.png" # should exist in `app/assets/images/`
